"""create tables

Revision ID: 0c951dc38871
Revises:
Create Date: 2025-08-07 18:34:09.264276

"""
from sqlalchemy import text
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")
schema = SCHEMA if environment == "production" else None

# revision identifiers, used by Alembic.
revision = '0c951dc38871'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    if schema:
        op.execute(text(f'CREATE SCHEMA IF NOT EXISTS "{schema}"'))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema=schema
    )

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema=schema
    )

    op.create_table('websites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('preview_img', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(
        ['user_id'],
        [f'{SCHEMA}.users.id'] if schema else ['users.id'],
    ),
    sa.PrimaryKeyConstraint('id'),
    schema=schema
    )

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(
        ['user_id'],
        [f'{SCHEMA}.users.id'] if schema else ['users.id'],
    ),
    sa.ForeignKeyConstraint(
        ['website_id'],
        [f'{SCHEMA}.websites.id'] if schema else ['websites.id'],
    ),
    sa.PrimaryKeyConstraint('id'),
    schema=schema
    )

    op.create_table('website_tags',
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(
        ['tag_id'],
        [f'{SCHEMA}.tags.id'] if schema else ['tags.id'],
    ),
    sa.ForeignKeyConstraint(
        ['website_id'],
        [f'{SCHEMA}.websites.id'] if schema else ['websites.id'],
    ),
    sa.PrimaryKeyConstraint('website_id', 'tag_id'),
    schema=schema
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('website_tags', schema=schema)
    op.drop_table('tags', schema=schema)
    op.drop_table('reviews', schema=schema)
    op.drop_table('websites', schema=schema)
    op.drop_table('users', schema=schema)
    # ### end Alembic commands ###
